apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.BETTER_AUTH_SECRET | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  KAFKA_BROKER: {{ .Values.secrets.KAFKA_BROKER | quote }}
  KAFKA_USERNAME: {{ .Values.secrets.KAFKA_USERNAME | quote }}
  KAFKA_PASSWORD: {{ .Values.secrets.KAFKA_PASSWORD | quote }}
